sudo: false
language: ruby
rvm:
  - 2.6.0
  - 2.5.0
  - 2.4.0
  - 2.3.0
  - 2.2.0
  - 2.1
os:
  - linux
  - osx
before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler -v '< 2'
before_script:
 - rake compile
